// Generated by CoffeeScript 1.4.0
(function() {
  var StoryDiffer;

  StoryDiffer = (function() {

    function StoryDiffer(my_console, child_process) {
      if (my_console == null) {
        my_console = console;
      }
      if (child_process == null) {
        child_process = require('child_process');
      }
      this.console = my_console;
      this.child_process = child_process;
    }

    StoryDiffer.prototype.run = function(options, andThen) {
      var process,
        _this = this;
      if (options.parameters.length > 0) {
        this.console.log("git-story: don't know what to do with '" + options.parameters[0] + "'");
        return andThen();
      } else {
        process = this.child_process.spawn('git', ['diff', 'origin/master...HEAD'], {
          stdio: 'inherit'
        });
        return process.on('exit', function() {
          return andThen();
        });
      }
    };

    return StoryDiffer;

  })();

  module.exports = StoryDiffer;

}).call(this);
