// Generated by CoffeeScript 1.4.0
(function() {
  var Help;

  Help = (function() {

    function Help() {}

    Help.prototype.run = function(options) {
      return console.log('No help for you.');
    };

    return Help;

  })();

  module.exports = Help;

}).call(this);
