// Generated by CoffeeScript 1.4.0
(function() {
  var StoryStarter;

  StoryStarter = (function() {

    function StoryStarter(storyFetcher, branchNameMaker) {
      this.storyFetcher = storyFetcher;
      this.branchNameMaker = branchNameMaker;
    }

    StoryStarter.prototype.run = function(options, andThen) {
      var storyUrl;
      storyUrl = options.parameters[0];
      return this.storyFetcher.fetch(storyUrl, this._thenNameBranch(options, andThen));
    };

    StoryStarter.prototype._thenNameBranch = function(options, andThen) {
      var _this = this;
      return function(error, story) {
        var branchName;
        branchName = _this.branchNameMaker.branchNameForStory(options, story);
        return andThen();
      };
    };

    return StoryStarter;

  })();

  module.exports = StoryStarter;

}).call(this);
