// Generated by CoffeeScript 1.4.0
(function() {
  var ActionLoader, path;

  path = require('path');

  ActionLoader = (function() {

    function ActionLoader(requirer) {
      if (requirer == null) {
        requirer = require;
      }
      this.requirer = requirer;
    }

    ActionLoader.prototype.load = function(action_name) {
      return this.requirer(this._path(action_name));
    };

    ActionLoader.prototype._path = function(action_name) {
      return path.dirname(__filename) + '/actions/' + action_name;
    };

    return ActionLoader;

  })();

  module.exports = ActionLoader;

}).call(this);
