// Generated by CoffeeScript 1.4.0
(function() {
  var ConfigReader;

  ConfigReader = (function() {

    function ConfigReader(fs) {
      if (fs == null) {
        fs = require('fs');
      }
      this.fs = fs;
    }

    ConfigReader.prototype.readConfig = function(continueWith) {
      return this.fs.readFile(this._configFile(), function(error, contents) {
        var config;
        if (error) {
          return continueWith({});
        } else {
          config = JSON.parse(contents.toString());
          return continueWith(config);
        }
      });
    };

    ConfigReader.prototype._configFile = function() {
      return process.env.HOME + '/.git-story';
    };

    return ConfigReader;

  })();

  module.exports = ConfigReader;

}).call(this);
