// Generated by CoffeeScript 1.4.0
(function() {
  var ConfigReader;

  ConfigReader = (function() {

    function ConfigReader(fs) {
      this.fs = fs != null ? fs : require('fs');
    }

    ConfigReader.prototype.readConfig = function(continueWith) {
      return this.fs.readFile(this._configFile(), function(error, contents) {
        var config;
        if (error) {
          return continueWith({});
        }
        config = JSON.parse(contents.toString());
        return continueWith(config);
      });
    };

    ConfigReader.prototype._configFile = function() {
      return process.env.HOME + '/.git-story';
    };

    return ConfigReader;

  })();

  module.exports = ConfigReader;

}).call(this);
