// Generated by CoffeeScript 1.4.0
(function() {
  var ActionLoader, Main, OptionParser, path;

  path = require('path');

  ActionLoader = require(path.join(path.dirname(__filename), 'action_loader'));

  OptionParser = require(path.join(path.dirname(__filename), 'option_parser'));

  Main = (function() {

    function Main(loader, parser) {
      if (loader == null) {
        loader = new ActionLoader;
      }
      if (parser == null) {
        parser = new OptionParser;
      }
      this.loader = loader;
      this.parser = parser;
    }

    Main.prototype.main = function(args) {
      var _this = this;
      return this.parser.parse(args, function(error, options) {
        var action_class, action_instance;
        action_class = _this.loader.load(options.action);
        action_instance = new action_class;
        return action_instance.run(options, function() {});
      });
    };

    return Main;

  })();

  module.exports = Main;

}).call(this);
