// Generated by CoffeeScript 1.4.0
(function() {
  var Options;

  Options = (function() {

    function Options(action, parameters, config) {
      this.action = action;
      this.parameters = parameters;
      this.config = config;
    }

    return Options;

  })();

  module.exports = Options;

}).call(this);
