// Generated by CoffeeScript 1.4.0
(function() {
  var ConfigReader, OptionParser, Options, path;

  path = require('path');

  ConfigReader = require(path.join(path.dirname(__filename), 'config_reader'));

  Options = require(path.join(path.dirname(__filename), 'options'));

  OptionParser = (function() {

    function OptionParser(configReader) {
      this.configReader = configReader != null ? configReader : new ConfigReader;
    }

    OptionParser.prototype.parse = function(argv, callback) {
      return this.configReader.readConfig(function(config) {
        var options;
        options = new Options(argv[1], argv.slice(2), config);
        return callback(null, options);
      });
    };

    return OptionParser;

  })();

  module.exports = OptionParser;

}).call(this);
